import React, { useEffect, useState } from 'react';
import { ArrowLeft, ShieldAlert, CheckCircle, Loader2 } from 'lucide-react';
import { api } from '../services/api';

export function AnalysisView({ analysisResult, onBack }) {
    // analysisResult is passed directly, no need to fetch
    const analysis = analysisResult;

    if (!analysis) return null;

    return (
        <div className="space-y-6">
            <button
                onClick={onBack}
                className="flex items-center space-x-2 text-muted-foreground hover:text-foreground transition-colors"
            >
                <ArrowLeft className="w-4 h-4" />
                <span>Back to Upload</span>
            </button>

            <div className="p-6 rounded-2xl border border-border bg-card/60 backdrop-blur-xl shadow-xl">
                <div className="flex items-start justify-between mb-6">
                    <div>
                        <h2 className="text-2xl font-bold text-foreground mb-1">Analysis Report</h2>
                        <span className="text-sm text-muted-foreground">Generated by local LLM pipeline</span>
                    </div>

                    {/* Metadata / Stats if available */}
                    {analysis.metadata && (
                        <div className="flex space-x-4 text-xs text-muted-foreground">
                            <span>Model: {analysis.metadata.model_used}</span>
                            <span>Time: {analysis.metadata.processing_time_ms}ms</span>
                        </div>
                    )}
                </div>

                <div className="space-y-8">
                    {/* Summary Section */}
                    {analysis.summary_of_changes && (
                        <div className="space-y-2">
                            <h3 className="text-lg font-semibold text-card-foreground">Executive Summary</h3>
                            <div className="p-4 rounded-xl bg-secondary/30 border border-border text-foreground leading-relaxed">
                                {analysis.summary_of_changes}
                            </div>
                        </div>
                    )}

                    {/* Actionable Tasks (Cards) */}
                    {(analysis.actionable_steps || []).length > 0 && (
                        <div className="space-y-4">
                            <h3 className="text-lg font-semibold text-card-foreground flex items-center gap-2">
                                <CheckCircle className="w-5 h-5 text-primary" />
                                Suggested Compliance Tasks
                            </h3>
                            <div className="grid gap-4 md:grid-cols-2">
                                {analysis.actionable_steps.map((step, idx) => (
                                    <div key={idx} className="group p-5 rounded-xl bg-card border border-border hover:border-primary/50 hover:shadow-lg transition-all duration-300">
                                        <div className="flex justify-between items-start mb-2">
                                            <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-primary/10 text-primary font-bold text-sm">
                                                {idx + 1}
                                            </span>
                                            {step.priority && (
                                                <span className={`text-[10px] uppercase font-bold px-2 py-1 rounded-full border ${step.priority.toLowerCase() === 'high' ? 'text-red-500 border-red-500/20 bg-red-500/10' :
                                                        step.priority.toLowerCase() === 'medium' ? 'text-yellow-500 border-yellow-500/20 bg-yellow-500/10' :
                                                            'text-blue-500 border-blue-500/20 bg-blue-500/10'
                                                    }`}>
                                                    {step.priority}
                                                </span>
                                            )}
                                        </div>
                                        <h4 className="font-semibold text-foreground mb-2">{step.action || "Required Action"}</h4>
                                        <p className="text-sm text-muted-foreground mb-3">{step.description}</p>
                                        {step.owner && (
                                            <div className="text-xs text-muted-foreground pt-3 border-t border-border mt-auto">
                                                Owner: <span className="font-medium text-foreground">{step.owner}</span>
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Fallback layout if structure is different (e.g. key_changes list) */}
                    {(analysis.key_changes || []).map((change, idx) => (
                        <div key={idx} className="p-4 border border-border rounded-lg bg-secondary/10">
                            <h4 className="font-medium text-foreground">{change.section || "General Change"}</h4>
                            <p className="text-sm text-muted-foreground mt-1">{change.description}</p>
                        </div>
                    ))}

                </div>
            </div>
        </div>
    );
}
